apiVersion: v1
kind: Service
metadata:
  name: demoapp-secretless
  labels:
    app: demoapp-secretless
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: demoapp-secretless
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demoapp-secretless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp-secretless
  name: demoapp-secretless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp-secretless
  template:
    metadata:
      labels:
        app: demoapp-secretless
    spec:
      serviceAccountName: demoapp-secretless
      containers:
      - image: cyberark/demo-app
        imagePullPolicy: Always
        name: demo-app
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
          - name: DB_URL
            value: "postgresql://localhost/demoapp"
      - image: cyberark/secretless-broker:latest
        imagePullPolicy: Always
        name: secretless
        args: ["-f", "/etc/secretless/secretless.yaml"]
        ports:
        - containerPort: 5432
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_URL
            value: "https://conjur-follower.conjur-dev.svc.cluster.local/authn-k8s/eks-dev"
          - name: CONJUR_APPLIANCE_URL
            value: "https://conjur-follower.conjur-dev.svc.cluster.local"
          - name: CONJUR_ACCOUNT
            value: demo
          - name: CONJUR_AUTHN_LOGIN
            value: "host/demoapp-secretless/demoapp-secretless"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate
        volumeMounts:
        - name: config
          mountPath: "/etc/secretless"
          readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
      - name: config
        configMap:
          name: secretless-config
