apiVersion: v1
kind: Service
metadata:
  name: demoapp-summon
  labels:
    app: demoapp-summon
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: demoapp-summon
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demoapp-summon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp-summon
  name: demoapp-summon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp-summon
  template:
    metadata:
      labels:
        app: demoapp-summon
    spec:
      serviceAccountName: demoapp-summon
      containers:
      - image: {{ DEMO_APP_IMAGE }}
        imagePullPolicy: Always
        name: demo-app
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
          - name: CONJUR_APPLIANCE_URL
            value: "https://conjur-follower.conjur-dev.svc.cluster.local"
          - name: CONJUR_ACCOUNT
            value: demo
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      initContainers:
      - image: cyberark/conjur-authn-k8s-client
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: CONTAINER_MODE
            value: init
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_URL
            value: "https://conjur-follower.conjur-dev.svc.cluster.local/authn-k8s/eks-dev"
          - name: CONJUR_ACCOUNT
            value: demo
          - name: CONJUR_AUTHN_LOGIN
            value: "host/demoapp-summon/demoapp-summon"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
