---
kind: Service
apiVersion: v1
metadata:
  name: demoapp-summon-backend
  namespace: demoapp-summon
spec:
  selector:
    app: demoapp-summon-backend
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demoapp-summon-pg
  labels:
    app: demoapp-summon-backend
spec:
  serviceName: demoapp-summon-backend
  selector:
    matchLabels:
      app: demoapp-summon-backend
  template:
    metadata:
      labels:
        app: demoapp-summon-backend
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: demoapp-summon-backend
        image: {{ TEST_APP_PG_DOCKER_IMAGE }}
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: backend-certs
            mountPath: "/etc/certs/"
            readOnly: true
        args: ["-c", "ssl=on", "-c", "ssl_cert_file=/etc/certs/server.crt", "-c", "ssl_key_file=/etc/certs/server.key"]
        env:
          - name: POSTGRES_USER
            value: demoapp-user
          - name: POSTGRES_PASSWORD
            value: {{ DEMOAPP_DB_PASSWORD }}
          - name: POSTGRES_DB
            value: demoapp
      volumes:
        - name: backend-certs
          secret:
            secretName: demoapp-backend-certs
            defaultMode: 384


