apiVersion: v1
kind: Service
metadata:
  name: demoapp-secrets-provider
  labels:
    app: demoapp-secrets-provider
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: demoapp-secrets-provider
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demoapp-secrets-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp-secrets-provider
  name: demoapp-secrets-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp-secrets-provider
  template:
    metadata:
      labels:
        app: demoapp-secrets-provider
    spec:
      serviceAccountName: demoapp-secrets-provider
      containers:
      - image: cyberark/demo-app
        imagePullPolicy: Always
        name: test-app
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
        - name: DB_URL
          valueFrom:
              secretKeyRef:
                name: demoapp-db-credentials
                key: url
        - name: DB_USERNAME
          valueFrom:
              secretKeyRef:
                name: demoapp-db-credentials
                key: username
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: demoapp-db-credentials
                key: password

