---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoapp-conjur-authenticator-role-binding-conjur-dev
  namespace: demoapp-secretless
subjects:
  - kind: ServiceAccount
    name: conjur-cluster
    namespace: conjur-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator-conjur-dev
